// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYQ-kBynLD2Ryxv5SijA_XcrRyOmFwThE',
    appId: '1:1015442848346:web:2dd21ff2ec3192fe063663',
    messagingSenderId: '1015442848346',
    projectId: 'apartmaint-95d1f',
    authDomain: 'apartmaint-95d1f.firebaseapp.com',
    databaseURL: 'https://apartmaint-95d1f-default-rtdb.firebaseio.com',
    storageBucket: 'apartmaint-95d1f.appspot.com',
    measurementId: 'G-TSZZ7T4MDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmDe76vclV1Qod-Eyj_8zas8EtxaUGpsc',
    appId: '1:1015442848346:android:a442c5fed78fcc93063663',
    messagingSenderId: '1015442848346',
    projectId: 'apartmaint-95d1f',
    databaseURL: 'https://apartmaint-95d1f-default-rtdb.firebaseio.com',
    storageBucket: 'apartmaint-95d1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJvsct4yGm5HnRRImat1KR9IpQWFBeIBM',
    appId: '1:1015442848346:ios:86f35760c3ced27d063663',
    messagingSenderId: '1015442848346',
    projectId: 'apartmaint-95d1f',
    databaseURL: 'https://apartmaint-95d1f-default-rtdb.firebaseio.com',
    storageBucket: 'apartmaint-95d1f.appspot.com',
    iosBundleId: 'com.example.apartmaint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJvsct4yGm5HnRRImat1KR9IpQWFBeIBM',
    appId: '1:1015442848346:ios:86f35760c3ced27d063663',
    messagingSenderId: '1015442848346',
    projectId: 'apartmaint-95d1f',
    databaseURL: 'https://apartmaint-95d1f-default-rtdb.firebaseio.com',
    storageBucket: 'apartmaint-95d1f.appspot.com',
    iosBundleId: 'com.example.apartmaint',
  );
}
